- hosts: workstation
  gather_facts: false
  roles:
  - name: osp-facts

  post_tasks:
  - name: OpenStack servers
  - name: Curl website
    tags:
      - packages

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible has done its job' not in webpage.results[0].content"
    tags:
      - osp.smoke
