---
- name: start {{ payload }}
  service:
    name: "{{ payload }}"
    state: started
    
- name: restart {{ payload }}
  service:
    name: "{{ payload }}"
    state: restarted

- name: enable {{ payload }}
  service:
    name: "{{ payload }}"
    enabled: yes
