---
# Tasks for app-tier role

- name: install {{ payload }}
  yum:
    name: "{{ payload }}"
    state: latest

- name: create tomcat default web directory
  file:
    path: "{{ tomcat_web_root }}"
    state: directory
  notify:
    - start {{ payload }}
    - enable {{ payload }}

- name: copy static index.html to tomcat webroot
  template:
    src: index.html.j2
    dest: "{{ tomcat_web_root }}/index.html"
    mode: 0644
  notify:
    - restart {{ payload }}
